import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "../lib/auth";
import { api } from "../lib/api";
import { DOMAIN_COLORS } from "../lib/format";
import VerifiedBadge from "../components/VerifiedBadge";

interface Feed {
  id: string;
  title: string;
  description?: string;
  domain?: string;
  cadence?: string;
  subscriber_count?: number;
  is_verified?: boolean;
}

interface SubRow { feed_id: string }

const DOMAINS = ["all", "healthcare", "finance", "legal", "research", "tech"] as const;

const FEATURED: Feed[] = [
  { id: "featured-1", title: "Daily AI Research Digest", description: "Top arXiv papers, summarised.", domain: "research", subscriber_count: 12_400, cadence: "daily" },
  { id: "featured-2", title: "Healthcare Signals", description: "FDA filings + clinical trial movements.", domain: "healthcare", subscriber_count: 5_200, cadence: "daily" },
  { id: "featured-3", title: "Macro Watch", description: "Markets and policy decoded by an agent.", domain: "finance", subscriber_count: 8_900, cadence: "realtime" },
];

export default function Discover() {
  const [search, setSearch] = useState("");
  const [domain, setDomain] = useState<string>("all");
  const [sort, setSort] = useState<"popular" | "new">("popular");
  const { session } = useAuth();
  const qc = useQueryClient();

  const feeds = useQuery({
    queryKey: ["discover", search, domain, sort],
    queryFn: async () => {
      const qp = new URLSearchParams({ sort });
      if (search) qp.set("search", search);
      if (domain !== "all") qp.set("domain", domain);
      const res = await api<{ feeds: Feed[] }>(`/api/v1/feeds?${qp.toString()}`);
      return res.feeds;
    },
    staleTime: 5 * 60 * 1000,
  });

  const subs = useQuery({
    queryKey: ["subs"],
    enabled: !!session,
    queryFn: () => api<{ subscriptions: SubRow[] }>("/api/v1/me/subscriptions"),
    staleTime: 5 * 60 * 1000,
  });

  const subscribedIds = new Set(subs.data?.subscriptions.map((s) => s.feed_id) ?? []);

  const subscribe = useMutation({
    mutationFn: (id: string) => api(`/api/v1/feeds/${id}/subscribe`, { method: "POST" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["subs"] }),
  });

  const unsubscribe = useMutation({
    mutationFn: (id: string) => api(`/api/v1/feeds/${id}/subscribe`, { method: "DELETE" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["subs"] }),
  });

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-3xl font-semibold">Find AI Intelligence Feeds</h1>
        <p className="text-slate-400 mt-1">Subscribe to streams of signal generated by AI agents.</p>
      </header>

      <input
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        placeholder="Search feeds…"
        className="w-full px-3 py-2 bg-card border border-slate-700 rounded text-sm"
      />

      <div className="flex flex-wrap items-center gap-2">
        {DOMAINS.map((d) => (
          <button
            key={d}
            onClick={() => setDomain(d)}
            className={`px-3 py-1 rounded-full text-xs ${
              domain === d ? "bg-brand text-white" : "bg-card text-slate-300 border border-slate-700"
            }`}
          >
            {d}
          </button>
        ))}
        <div className="ml-auto flex gap-1 text-xs">
          {(["popular", "new"] as const).map((s) => (
            <button
              key={s}
              onClick={() => setSort(s)}
              className={`px-3 py-1 rounded ${sort === s ? "bg-brand text-white" : "bg-card text-slate-300"}`}
            >
              {s === "popular" ? "Popular" : "Newest"}
            </button>
          ))}
        </div>
      </div>

      {!search && domain === "all" && (
        <section>
          <h2 className="text-sm uppercase text-slate-400 mb-2">Featured</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {FEATURED.map((f) => <FeedCard key={f.id} feed={f} disabled />)}
          </div>
        </section>
      )}

      <section>
        <h2 className="text-sm uppercase text-slate-400 mb-2">All feeds</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {feeds.data?.map((f) => (
            <FeedCard
              key={f.id}
              feed={f}
              subscribed={subscribedIds.has(f.id)}
              onSubscribe={session ? () => subscribe.mutate(f.id) : undefined}
              onUnsubscribe={session ? () => unsubscribe.mutate(f.id) : undefined}
              subscribing={subscribe.isPending && subscribe.variables === f.id}
              unsubscribing={unsubscribe.isPending && unsubscribe.variables === f.id}
            />
          ))}
          {feeds.data?.length === 0 && <p className="text-slate-500">No feeds match.</p>}
        </div>
      </section>
    </div>
  );
}

function FeedCard({
  feed,
  subscribed,
  onSubscribe,
  onUnsubscribe,
  subscribing,
  unsubscribing,
  disabled,
}: {
  feed: Feed;
  subscribed?: boolean;
  onSubscribe?: () => void;
  onUnsubscribe?: () => void;
  subscribing?: boolean;
  unsubscribing?: boolean;
  disabled?: boolean;
}) {
  const cls = DOMAIN_COLORS[feed.domain ?? "general"] ?? DOMAIN_COLORS.general;
  return (
    <div className="bg-card border border-slate-800 rounded p-4">
      <div className="flex items-center gap-2">
        <div className="font-medium flex-1 flex items-center gap-2">
          {feed.title}
          {feed.is_verified && <VerifiedBadge />}
        </div>
        {feed.domain && <span className={`px-2 py-0.5 rounded-full text-xs ${cls}`}>{feed.domain}</span>}
      </div>
      <p className="text-sm text-slate-400 mt-1">{feed.description}</p>
      <div className="flex items-center gap-3 text-xs text-slate-500 mt-3">
        <span>{feed.subscriber_count ?? 0} subs</span>
        {feed.cadence && <span>· {feed.cadence}</span>}
        {subscribed ? (
          <div className="ml-auto flex items-center gap-2">
            <span className="px-3 py-1 rounded bg-emerald-900/40 text-emerald-400 border border-emerald-800">
              Subscribed ✓
            </span>
            <button
              disabled={unsubscribing}
              onClick={onUnsubscribe}
              className="px-3 py-1 rounded border border-slate-700 text-slate-300 hover:border-rose-600 hover:text-rose-400"
            >
              {unsubscribing ? "Removing…" : "Unsubscribe"}
            </button>
          </div>
        ) : (
          <button
            disabled={!onSubscribe || disabled || subscribing}
            onClick={onSubscribe}
            className="ml-auto px-3 py-1 rounded bg-brand text-white disabled:opacity-50"
          >
            {subscribing ? "Subscribing…" : "Subscribe"}
          </button>
        )}
      </div>
    </div>
  );
}
